/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  eyebrow?: string;
  announcementEnabled?: boolean;
  announcementMessage?: string;
  announcementLinkLabel?: string;
  announcementLinkUrl?: string;
  headline?: string;
  introduction?: string;
  contactEmail?: string;
  callToActionLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
  homepage?: {
    heroTitle?: string;
    heroIntroduction?: string;
    heroActionLabel?: string;
    collectionTitle?: string;
    guidanceEyebrow?: string;
    guidanceTitle?: string;
    guidanceIntroduction?: string;
    guidanceActionLabel?: string;
    guidanceSupportingText?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    brandName,    eyebrow,    "announcement": {      "enabled": coalesce(announcementEnabled, false),      "message": announcementMessage,      "linkLabel": announcementLinkLabel,      "linkUrl": announcementLinkUrl    },    headline,    introduction,    contactEmail,    callToActionLabel,    seoTitle,    seoDescription,    homepage{      heroTitle,      heroIntroduction,      heroActionLabel,      collectionTitle,      guidanceEyebrow,      guidanceTitle,      guidanceIntroduction,      guidanceActionLabel,      guidanceSupportingText    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  brandName: string | null;
  eyebrow: string | null;
  announcement: {
    enabled: boolean | false;
    message: string | null;
    linkLabel: string | null;
    linkUrl: string | null;
  };
  headline: string | null;
  introduction: string | null;
  contactEmail: string | null;
  callToActionLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  homepage: {
    heroTitle: string | null;
    heroIntroduction: string | null;
    heroActionLabel: string | null;
    collectionTitle: string | null;
    guidanceEyebrow: string | null;
    guidanceTitle: string | null;
    guidanceIntroduction: string | null;
    guidanceActionLabel: string | null;
    guidanceSupportingText: string | null;
  } | null;
} | null;
