/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialPage = {
  _id: string;
  _type: "editorialPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  introduction?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sections?: Array<{
    role?: "origin" | "development" | "collaborator" | "principles";
    heading?: string;
    body?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      sourceOwner?: string;
      storefrontRightsConfirmed?: boolean;
      territory?: string;
      rightsDuration?: "Perpetual" | "Expiry recorded";
      expiryDate?: string;
      releaseStatus?:
        | "Not applicable"
        | "Model release recorded"
        | "Property release recorded";
      licenceReference?: string;
      _type: "image";
    };
    _type: "editorialSection";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  eyebrow?: string;
  announcementEnabled?: boolean;
  announcementMessage?: string;
  announcementLinkLabel?: string;
  announcementLinkUrl?: string;
  headline?: string;
  introduction?: string;
  contactEmail?: string;
  callToActionLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
  homepage?: {
    heroTitle?: string;
    heroIntroduction?: string;
    heroActionLabel?: string;
    heroSlides?: Array<{
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt?: string;
      caption?: string;
      visible?: boolean;
      _type: "heroSlide";
      _key: string;
    }>;
    collectionTitle?: string;
    guidanceEyebrow?: string;
    guidanceTitle?: string;
    guidanceIntroduction?: string;
    guidanceActionLabel?: string;
    guidanceSupportingText?: string;
    showServiceReassurance?: boolean;
    serviceTitle?: string;
    serviceIntroduction?: string;
    showFounderStory?: boolean;
    founderTitle?: string;
    founderStory?: string;
    founderImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    showLongevity?: boolean;
    longevityTitle?: string;
    longevityIntroduction?: string;
    longevityConditions?: string;
    showCollectionInvitation?: boolean;
    collectionInvitationTitle?: string;
    collectionInvitationIntroduction?: string;
    collectionInvitationActionLabel?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | EditorialPage
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{ brandName, eyebrow, "announcement": { "enabled": coalesce(announcementEnabled, false), "message": announcementMessage, "linkLabel": announcementLinkLabel, "linkUrl": announcementLinkUrl }, headline, introduction, contactEmail, callToActionLabel, seoTitle, seoDescription, homepage{ heroTitle, heroIntroduction, heroActionLabel, "heroSlides": heroSlides[visible != false]{ "id": _key, "src": image.asset->url, "hotspot": image.hotspot, alt, caption }, collectionTitle, guidanceEyebrow, guidanceTitle, guidanceIntroduction, guidanceActionLabel, guidanceSupportingText, "showServiceReassurance": coalesce(showServiceReassurance, true), serviceTitle, serviceIntroduction, "showFounderStory": coalesce(showFounderStory, true), founderTitle, founderStory, "founderImage": founderImage{ "src": asset->url, alt }, "showLongevity": coalesce(showLongevity, true), longevityTitle, longevityIntroduction, longevityConditions, "showCollectionInvitation": coalesce(showCollectionInvitation, true), collectionInvitationTitle, collectionInvitationIntroduction, collectionInvitationActionLabel } }
export type SITE_SETTINGS_QUERY_RESULT = {
  brandName: string | null;
  eyebrow: string | null;
  announcement: {
    enabled: boolean | false;
    message: string | null;
    linkLabel: string | null;
    linkUrl: string | null;
  };
  headline: string | null;
  introduction: string | null;
  contactEmail: string | null;
  callToActionLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  homepage: {
    heroTitle: string | null;
    heroIntroduction: string | null;
    heroActionLabel: string | null;
    heroSlides: Array<{
      id: string;
      src: string | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      caption: string | null;
    }> | null;
    collectionTitle: string | null;
    guidanceEyebrow: string | null;
    guidanceTitle: string | null;
    guidanceIntroduction: string | null;
    guidanceActionLabel: string | null;
    guidanceSupportingText: string | null;
    showServiceReassurance: boolean | true;
    serviceTitle: string | null;
    serviceIntroduction: string | null;
    showFounderStory: boolean | true;
    founderTitle: string | null;
    founderStory: string | null;
    founderImage: {
      src: string | null;
      alt: string | null;
    } | null;
    showLongevity: boolean | true;
    longevityTitle: string | null;
    longevityIntroduction: string | null;
    longevityConditions: string | null;
    showCollectionInvitation: boolean | true;
    collectionInvitationTitle: string | null;
    collectionInvitationIntroduction: string | null;
    collectionInvitationActionLabel: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EDITORIAL_PAGE_QUERY
// Query: *[_type == "editorialPage" && slug.current == $slug][0]{    eyebrow, title, introduction, "image": heroImage{ "src": asset->url, alt },    sections[]{ _key, role, heading, body, "image": image{ "src": asset->url, alt, storefrontRightsConfirmed, hotspot, crop } },    seoTitle, seoDescription  }
export type EDITORIAL_PAGE_QUERY_RESULT = {
  eyebrow: string | null;
  title: string | null;
  introduction: string | null;
  image: {
    src: string | null;
    alt: string | null;
  } | null;
  sections: Array<{
    _key: string;
    role: "collaborator" | "development" | "origin" | "principles" | null;
    heading: string | null;
    body: string | null;
    image: {
      src: string | null;
      alt: string | null;
      storefrontRightsConfirmed: boolean | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;
